import CardBlog, { CardBlogType } from '@/components-child/card-blog'
import Layout, { LayoutAsideType, LayoutType } from '@/components-root/layout'
import AppLink from '@/components-root/link'
import Pagination from '@/components-root/pagination'
import Footer from '@/ui/footer'
import Header from '@/ui/header'
import classNames from 'classnames'
import Head from 'next/head'

export default function CategoryPage() {
  return (
    <>
      <Head>
        <title>Arcgive page titke</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout
        type={LayoutType.container}
        header={<Header />}
        footer={<Footer />}
        asideType={LayoutAsideType.no}
        classMain="archive-page"
      >
        <section className="archive-head">
          <div className="row">
            <div className="col">
              <div className="col-inner">
                <h1 className={classNames('archive-title')}>Read our blog</h1>
              </div>
            </div>
          </div>
        </section>
        <section className="archive-loop">
          <div className="post-wrap row row-mt row-large">
            {Array(8)
              .fill(null)
              .map((item, index) => {
                return (
                  <div className="col col-12 col-sm-6 col-md-4" key={index}>
                    <div className="col-inner">
                      <CardBlog
                        thumbnail={`/images/blogs/blog_${index + 1}.jpg`}
                        imgRatio={56.2}
                        imgRadius={10}
                        type={CardBlogType.default}
                        isShowCate={true}
                        title="'Giảm vật liệu công nghiệp, tăng chất liệu tự nhiên - cách KTS thay đổi không gian sống cho gia chủ"
                        cateTitle="Category name"
                        styleTitle="Style name"
                      />
                    </div>
                  </div>
                )
              })}
          </div>
        </section>
        <section className="archive-pagination">
          <div className="row">
            <div className="col">
              <div className="col-inner">
                <Pagination count={8} current={4} showLength={5} />
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  )
}
