import Head from "next/head";
import Layout, {
  LayoutAsideType,
  LayoutFooterType,
  LayoutHeaderType,
  LayoutType,
} from "@/components/layout";

import Gap from "@/components/gap";

import styles from "@/styles/home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout
        type={LayoutType.container}
        headerType={LayoutHeaderType.default}
        footerType={LayoutFooterType.default}
        asideType={LayoutAsideType.no}
      >
        <Gap large={30} />
        <div className="row ">
          <div className="col col-lg-8">
            <div className="col-inner">sdsd</div>
          </div>
        </div>
        <h1 style={{ fontSize: "50px" }}>Hello wor!d</h1>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nisi,
          tempore? Reiciendis repellendus assumenda, illum itaque quas incidunt
          doloribus voluptatum corporis quasi similique dicta sequi dolores
          maiores, ab optio neque autem!
        </p>
        <Gap large={2000} />
      </Layout>
    </>
  );
}
