import CardBlog, { CardBlogType } from "@/components-child/card-blog";
import Layout, { LayoutAsideType, LayoutType } from "@/components-root/layout";
import AppLink from "@/components-root/link";
import Pagination from "@/components-root/pagination";
import Footer from "@/ui-child/footer";
import Header from "@/ui-child/header";
import classNames from "classnames";
import Head from "next/head";

export default function SearchPage(): JSX.Element {
  return (
    <>
      <Head>
        <title>Search title</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout
        type={LayoutType.container}
        header={<Header />}
        footer={<Footer />}
        asideType={LayoutAsideType.no}
        classMain="search-page"
      >
        <section className="search-head">
          <div className="row">
            <div className="col col-12 col-sm-12 col-md-8 col-lg-9">
              <div className="col-inner">
                <h1 className={classNames("search-title")}>
                  Tìm thấy 52073 kết quả với từ khóa &quot;search key&quot;
                </h1>
              </div>
            </div>
          </div>
        </section>
        <section className="search-loop">
          <div className="post-wrap row row-mt row-large">
            {Array(8)
              .fill(null)
              .map((item, index: number) => {
                return (
                  <div
                    className="col col-12 col-sm-12 col-md-8 col-lg-9"
                    key={index}
                  >
                    <div className="col-inner">
                      <CardBlog
                        thumbnail={`/images/blogs/blog_${index + 1}.jpg`}
                        imgRatio={56.2}
                        imgRadius={10}
                        type={CardBlogType.vertical}
                        title="'Giảm vật liệu công nghiệp, tăng chất liệu tự nhiên - cách KTS thay đổi không gian sống cho gia chủ"
                        isShowCate={false}
                        isShowDate={true}
                        isShowView={true}
                      />
                    </div>
                  </div>
                );
              })}
          </div>
        </section>
        <section className="archive-pagination">
          <div className="row">
            <div className="col">
              <div className="col-inner">
                <Pagination count={8} current={1} showLength={5} />
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}
